### ISSUE TITLE
Persist post sort per community

### ISSUE THREAD

**Issue by aeharding** [aeharding/voyager#1008]
I would like an option to persist my post sort per community

**Comment by aeharding** [comment]
Hi @0xCmdrKeen! I am currently working on this (see assignees). Please express your interest in working on something by commenting if unassigned first :)

**Comment by aeharding** [comment]
@0xCmdrKeen Yes, feel free to post the branch URL here! I am partway into this task locally but it may be helpful to see what you did.

**Comment by 0xCmdrKeen** [comment]
@aeharding okay, here you go: https://github.com/0xCmdrKeen/voyager/tree/community-sort

Basically, I added a `community.sortByHandle` object to the state to store sort per-community sort order. Then I changed the `usePostSort` hook to take a community handle as an optional parameter and if present, use Redux instead of React state to store the sort order for that community.

Finally, I added two thunks to read and write per-community sort order to the database, using the existing `default_post_sort` setting, but stored with community AND user specificity (instead of user only, which used to store the general default setting).
