### ISSUE TITLE
Community sidebar stats

### ISSUE THREAD

**Issue by hungryca-t** [aeharding/voyager#1106]
**Describe the bug**
The community sidebar appears to display subscriber count etc. from the user’s instance instead of from the home instance. This limits the true participation numbers for the community.

**To Reproduce**

1. As a non-user of a particular instance, identify a community that instance hosts. 
2. View community sidebar and note the subscriber/participation stats.
3. Switch to a user account that lives on the instance and repeat steps 1-2 OR view the community from the instance site in a browser. 
4. Compare the sidebar stats. 

Below is an example for the Ask Lemmy community of the lemm.ee instance. First is the Voyager community sidebar as seen from a non-Lemm.ee user account. Second is the sidebar from the community’s page on the instance site via browser. Note that the total subscriber count and other stats are different. 

**Expected behavior**
Voyager would pull community stats directly from the home instance for use in the sidebar.

**Screenshots**
1:
![image](https://github.com/aeharding/voyager/assets/138980525/b6e07269-af40-49cb-87e0-92b3811c15d0)

2:
![image](https://github.com/aeharding/voyager/assets/138980525/a1e3374b-5889-4f8e-b0fa-3c4336145b0a)

**Comment by aeharding** [comment]
Hi there, this is intended behavior from Voyager's side. Voyager will always connect your your instance for data, not an arbitrary remote instance. If Voyager connected to a remote instance you didn't specify, it would leak your IP and device information unknowingly to that instance.

However the issue is valid. I recommend looking to see if there are any issues on Lemmy's side to federate this information so it it consistent.

Thanks!
