### ISSUE TITLE
Allow mods to ban users

### ISSUE THREAD

**Issue by sallyFoster** [aeharding/voyager#1121]
**Is your feature request related to a problem? Please describe.**

As a moderator, I would like the ability to ban troublemakers.

**Describe the solution you'd like**

I would like an option in the Mod tools to ban users which also allows me to add a reason as to why I am banning them. 

**Describe alternatives you've considered**

Now, the only way to do that is on the web version.

**Additional context**

**Comment by 0xCmdrKeen** [comment]
I thought about this one, but it turns out it's not quite that simple. Where would that button go? In the post action sheet, when you're viewing a community in which you have mod rights? That's already quite long, almost takes up the entire screen already:

![screenshot](https://github.com/aeharding/voyager/assets/98132670/eeb58442-c4ae-41de-93ed-dc74e470a320)

The same menu on the post itself is a little bit shorter, because the "hide" option appears to be missing (not sure if intentional or not):

![screenshot](https://github.com/aeharding/voyager/assets/98132670/53fb69e8-34ff-4b56-9480-da70e70bc0ea)

The "ban user from instance" could go into the ellipsis menu on the user profile itself, but the "ban from community" option can't because there's no community context there.

Also, I'm not entirely sure how to figure out if one has permission to issue instance-wide bans, does that require admin rights?

**Comment by sallyFoster** [comment]
@0xCmdrKeen So, for mods there is a mod action button that appears on every comment on posts which right now only has 3 actions. You can add it there.

![image](https://github.com/aeharding/voyager/assets/104597302/e39953b3-bbbc-4374-aae7-031c20c60cca)


![image](https://github.com/aeharding/voyager/assets/104597302/858dd907-eec8-4034-af9c-d12acdb9d540)

**Comment by 0xCmdrKeen** [comment]
@sallyFoster oh, I see. And it looks like posts have the same menu too (in the titlebar). Yeah, that would make sense for it to go there. Okay, I'd be happy to take care of it if @aeharding will let me. 

Still need to know how to figure out if someone has the right to perform instance bans so that if they don't, that option won't even show up there. Also, which icon(s) to use and whether those entries should be red or not. I suppose a community ban could use the same icon as the one for blocking a community as a regular user (`remove-circle-outline`), and instance ban could use `ban-circle-outline`.

**Comment by sallyFoster** [comment]
@0xCmdrKeen the mod actions button only shows up for the mods of that community; therefore, if you added the action there, the logic that knows which user can ban or cannot ban is already taken care of.

**Comment by 0xCmdrKeen** [comment]
@sallyFoster there are two types of bans, one applies to the community only, and the other to the whole instance.

I'm fairly certain mods can issue community bans for communities that they moderate, but I'm not entirely sure what it takes to issue instance bans. I'm assuming it might require an admin role, but I haven't found any definite answer in the documentation yet.

**Comment by sallyFoster** [comment]
@0xCmdrKeen I think that only admins can ban from instances, because I moderate like 6 communities and I have never seen the option to ban a user from an instance.

**Comment by 0xCmdrKeen** [comment]
@sallyFoster yes, I think you are right, because I haven't seen any place to issue more fine-grained permissions. I also think I just found the documentation for it: https://join-lemmy.org/docs/users/04-moderation.html

**Comment by sallyFoster** [comment]
Yup, as per the documentation:

> Where admins can ban a user from the entire instance, mods can only ban them from their community.

**Comment by 0xCmdrKeen** [comment]
@sallyFoster alright, that still leaves a couple of questions:

- What icons to use? Keep in mind we might need two different ones to distinguish between community bans and site bans. Also need icons for the respective unbanning options. Should probably coordinate with the ones used in the modlog redesign, if @aeharding wants to keep them there.
- Do we just add community bans for now or also implement site bans (if the user has admin rights)? I suppose it's fine to just do the former for now since there are more mods than admins, and community bans are more frequently used than site bans.
- Should this feature ask for a ban reason or not? Probably fine to skip this for now and fix it along with #1045 once we've figured that out.

So I guess the icon choice is probably the most important question for now. Let's wait to hear from Alex about that.

**Comment by aeharding** [comment]
This issue is specifically about mods banning users. Instance bans can be addressed in a separate ticket. For icon I'm not sure, something from ion icons will do. And yes, ban reason will be added as well as remove user posts and duration.

I'm currently working on this as part of the part 3 of mod tools.
