### ISSUE TITLE
Add option to collapse comments recursively

### ISSUE THREAD

**Issue by ShadowAndFlame** [aeharding/voyager#1153]
It would be nice to have an option to, if "Collapse Comment Threads" is enabled, to further collapse all child comments as well by default. 

If enabled, when you open a post it should only show Level 0 (i.e. parent) comments. When tapping a comment to expand its children it should only show Level 1 comments. Tapping on a Level 1 comment should show Level 2 comments, etc.

This would allow easier navigation of highly commented posts, with more of a "breadth first" experience rather than "depth first." I believe Baconreader had this behavior.

**Comment by aeharding** [comment]
Hi there! This shouldn't be that hard to implement by changing the fetch depth to only increment depth by 1 as an option.

We'll probably want to change "collapse comment threads" toggle to a dropdown with three options - Never, Root Only, All or something like that.

If someone wants to take a shot at it feel free (just let me know), otherwise I'll get around to it at some point.

**Comment by ShadowAndFlame** [comment]
@aeharding I'm willing to take a shot at it but I am a beginner so it may take some time. It would be a good learning experience for me. If you'd rather I stay out of it, no problem.

**Comment by aeharding** [comment]
@ShadowAndFlame sure, you can take a look :)
