### ISSUE TITLE
Don't log user out when instance is down

### ISSUE THREAD

**Issue by GammaGames** [aeharding/voyager#1510]
**Is your feature request related to a problem? Please describe.**
Some instances aren't as stable as others and the app removes my account if an instance happens to be down when I open it, forcing me to re-add it 

**Describe the solution you'd like**
Don't log my account out when the instance is down

**Describe alternatives you've considered**
Leaving it as-is?

**Comment by aeharding** [comment]
This bug is because Lemmy is telling us that your login token is invalid. This error is false. But apparently the next version of lemmy will fix it.

https://github.com/LemmyNet/lemmy/issues/4319

I could just ignore and keep user logged in, but that would result in app being in bad state if the token is ACTUALLY invalid.

So there's no good solution here. this bug sucks.

**Comment by GammaGames** [comment]
Makes sense, thanks!

**Comment by aeharding** [comment]
I think I removed this logic at some point! If it is still a problem please let me know.
