### ISSUE TITLE
Adding a link for an option thumbnail on web, makes the app only open the thumbnail and not the video

### ISSUE THREAD

**Issue by sallyFoster** [aeharding/voyager#1536]
**Describe the bug**
When I link a video url along side a thumbnail url, the app only makes it such that the user can only open the image of the thumbnail

**Expected behavior**
The user should be able to play the video.

**Comment by aeharding** [comment]
This should have been fixed recently. If it hasn't, please provide a link to the post with issues!

**Comment by sallyFoster** [comment]
@aeharding This is the link

https://lemmygrad.ml/post/5110967

![image](https://github.com/user-attachments/assets/9904a421-0d40-4272-beec-192f634d8133)

https://lemmygrad.ml/post/5110969

![image](https://github.com/user-attachments/assets/2f127477-fc81-432e-8cb5-ba34b4364435)

**Comment by aeharding** [comment]
That works for me in latest Voyager. The video doesn't work in iOS because the codec is malformed/not supported on iOS. But there's nothing I can do to solve that (have to wait for a iOS update to add support, or upload more widely supported video encoding).

<img width="634" alt="image" src="https://github.com/user-attachments/assets/c16e7b14-5311-4d30-8f75-c9468bd69696">
