### ISSUE TITLE
Home (Posts from subscriptions) showing content from communities im not subscribed to

### ISSUE THREAD

**Issue by promitheas17j** [aeharding/voyager#1619]
**Describe the bug**
In my Home tab I am not seeing just my subscriptions, but also posts from communities Im not subscribed to. In fact, it is exactly the same as the All feed.

**To Reproduce**

1. Go to Home feed
2. See posts from communities not subscribed to
3. Go to All feed
4. Compare Home and All feeds and notice they are exactly the same.

**Expected behavior**
I would expect my Home feed to only show me posts from my subscribed communities.

**Screenshots**
![IMG_20241008_105549.jpg](https://github.com/user-attachments/assets/bff9de6b-3075-4120-8a55-bca5cceca1fe)

![Screenshot_2024-10-08-10-54-39-05_2b4f8779cf9636c3357414a19d1d1518.jpg](https://github.com/user-attachments/assets/27ec6976-ff1e-43de-88f8-4038f8c3ff80)

![Screenshot_2024-10-08-10-55-09-42_2b4f8779cf9636c3357414a19d1d1518.jpg](https://github.com/user-attachments/assets/77175d61-69ac-410c-88b4-8ba79215b5b8)

**Smartphone (please complete the following information):**

- Device: OnePlus 8Pro
- OS: Android 13.1 (OxygenOS 13.1)
- Browser: Brave, but using the app
- Version: 1.70.123

**Additional context**
I checked my subscriptions by going to my instances site through a browser and logging in, and they are there.

**Comment by aeharding** [comment]
Try logout and login again. Lmk!Sent from my iPhoneOn Oct 8, 2024, at 3:00 AM, Martin Aziz ***@***.***> wrote:﻿
Describe the bug
In my Home tab I am not seeing just my subscriptions, but also posts from communities Im not subscribed to. In fact, it is exactly the same as the All feed.
To Reproduce

Go to Home feed
See posts from communities not subscribed to
Go to All feed
Compare Home and All feeds and notice they are exactly the same.

Expected behavior
I would expect my Home feed to only show me posts from my subscribed communities.
Screenshots
IMG_20241008_105549.jpg (view on web)
Screenshot_2024-10-08-10-54-39-05_2b4f8779cf9636c3357414a19d1d1518.jpg (view on web)
Screenshot_2024-10-08-10-55-09-42_2b4f8779cf9636c3357414a19d1d1518.jpg (view on web)
Smartphone (please complete the following information):

Device: OnePlus 8Pro
OS: Android 13.1 (OxygenOS 13.1)
Browser: Brave, but using the app
Version: 1.70.123

Additional context
I checked my subscriptions by going to my instances site through a browser and logging in, and they are there.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/aeharding/voyager/issues/1619",
"url": "https://github.com/aeharding/voyager/issues/1619",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by promitheas17j** [comment]
Yep that fixed it. It could be because the past few days my instance server got an update
