### ISSUE TITLE
Autofill title: "Unable to fetch title"

### ISSUE THREAD

**Issue by fer0n** [aeharding/voyager#1776]
**To Reproduce**
- make a new post
- Paste an article link from e.g. road to vr (https://www.roadtovr.com/behemoth-update-combat-rebalance-patch-notes/)
- tap on auto fill
- "Unable to fetch title" error message

**Expected behavior**
Autofill should work for roadtovr.com

**Screenshots**
![image](https://github.com/user-attachments/assets/e38880f5-897a-4b4e-b1a9-c241af622e69)

**Smartphone (please complete the following information):**

- Device: iPhone 16 Pro
- OS: iOS 18.2
- Browser Native App
- Version 2.21.1

**Comment by aeharding** [comment]
Hi @fer0n. Does it work on Lemmy (it is using Lemmy API)?

**Comment by fer0n** [comment]
Not entire sure what you mean by that, the account I was using is on Lemmy.world and so is the community I've been trying to post to. The error shows up when I tap on the "Autofill" button after entering the url mentioned above, is that using a Lemmy api? I was assuming it simply fetched the html title at that url.

**Comment by aeharding** [comment]
Yes, its lemmy api. Here's an example with vger.social where it is working. I can confirm it is not working for lemmy.world. Could be because lemmy.world is using an outdated lemmy version, or some network config for that instance.

<img width="770" alt="image" src="https://github.com/user-attachments/assets/80d3fac4-8b5d-4c37-89b1-b8c67c17092a" />

**Comment by fer0n** [comment]
Okay, thanks for taking a look. I'll see if I can let them know :)
