### ISSUE TITLE
🚨 DESIGNER HELP NEEDED: New calendar icons!

### ISSUE THREAD

**Issue by aeharding** [aeharding/voyager#197]
Hi there!

Paging all designers that build SVGs!

Apollo had some really nice calendar items for "top" sorts.

This is important, because when sorting by top, the different icon shows in the header of wefwef that allows you to see which "top" sort you have selected.

Example Apollo options:

<img width="250" alt="image" src="https://github.com/aeharding/wefwef/assets/2166114/33571c29-2559-4b40-b238-4491fc0246d7">

We obviously don't want to exactly copy. Ionic has a nice MIT-licensed calendar SVG we can use as a base:

https://github.com/aeharding/wefwef/assets/2166114/03c8a1df-2563-4786-9333-d2d6d7e38022

Then we just need to style the contents of the calendar item. :)

Here's all of the "top" states in wefwef. We need different icons for each option as SVGs.

<img src="https://github.com/aeharding/wefwef/assets/2166114/831e261c-69b0-4dec-9749-42a0b857e57c" width="250">

**Comment by DCarlson12** [comment]
I can try to whip something up. Can I do the same number style with some ideas for the 6 and 12 hour marks?

Was thinking of putting 1/4 and 1/2 for the 6 and 12 hour ones respectively.

**Comment by Bahnburner** [comment]
If I can find time over the holiday, I'll knock these out. It shouldn't take long at all.

**Comment by tilden** [comment]
Hi there! In case no one has finished this yet, I made a concept for how this could look. I was thinking that instead of fully following the Apollo model of using a calendar icon as the basis for every time unit, it could be worthwhile to differentiate the choices further by using different base icons for different time units (clock for hour, calendar for days, etc.) What do you think?

<img width="741" alt="image" src="https://github.com/aeharding/voyager/assets/466332/49d582c2-5018-4956-aed9-a1c468703bca">

**Comment by rsammelson** [comment]
I really like this look!

**Comment by aeharding** [comment]
@tilden agreed, these are perfect. can you make a PR? Thanks!

**Comment by tilden** [comment]
@aeharding Sure!
