### ISSUE TITLE
Remove Account icon is being cropped at the top and bottom

### ISSUE THREAD

**Issue by kerosyn** [aeharding/voyager#403]
![image](https://github.com/aeharding/voyager/assets/723314/a1208c29-f4a3-455d-aa80-24703b7740b4)

As shown in the picture the top and bottom of the remove icon are slightly cut off.

Using:
Voyager 0.20.0
iPhone 13
iOS Developer Beta 3
Safari

**Comment by aeharding** [comment]
I can reproduce with a larger font size

**Comment by kerosyn** [comment]
> I can reproduce with a larger font size

Sorry didn’t even occurred to me to include. I am using the 4th largest font size.

**Comment by RoToRa** [comment]
Hi, I'm new here and this seems like a nice first issue, but I just would like to discuss it before stepping on any ones toes with an early PR. 

If I see it correctly the problem is this `font-size`:
https://github.com/aeharding/voyager/blob/667f7dda8e4f736237c69d45fc7afa3dc88f857e/src/features/auth/Account.tsx#L19

Personally, I'd just remove it and instead add `slot="icon-only"` to the icon which makes the icon slightly larger again. Alternatively, if the icon is too small, I could change the `font-size` to use `em` instead of `rem` (because this is what ionic uses throughout), specifically `2.2em`.

**Comment by aeharding** [comment]
Feel free to take it @RoToRa :)

The requirements I see are:

 1. Icon remains same size as now for default/normal text size
 2. Icon doesn't clip at all text sizes
