### ISSUE TITLE
Delete + Cancel stay on screen after posting comments (web app)

### ISSUE THREAD

**Issue by nightgolfer** [aeharding/voyager#621]
When I'm writing a comment, I have a button for Cancel top left, and Post top right.

After finishing the comment and clicking Post, a green message pops up bottom screen saying "Comment posted!". Underneath that are two new "buttons", Delete and Cancel".

The screen stays on the comment input "page", with Cancel and Post still at the top of the screen; I'm not sent back to the post I was commenting on, and the two new Delete and Cancel options at the bottom of the screen stay there as well.

My comment does get posted.

If I click the bottom Cancel, the options to away. I still need to click the top Cancel to get back to the post. If I swipe instead, I get sent back to the Posts overview page instead.

If I swipe instead of clicking either Cancel, the bottom Delete and Cancel options stay on the screen indefinitely until I click either.

**Comment by nightgolfer** [comment]
![Screenshot_2023-08-08-01-26-52-78_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/aeharding/voyager/assets/32328229/1a86ad22-1bb4-4b15-a5a9-5dd503fc3cfb)

![Screenshot_2023-08-08-01-27-05-38_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/aeharding/voyager/assets/32328229/53789c83-fe5c-4c23-9568-4455aa2884bb)

![Screenshot_2023-08-08-01-27-13-18_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/aeharding/voyager/assets/32328229/ffed064e-24a3-4e4f-ba62-d032cfe174e7)

![Screenshot_2023-08-07-19-34-30-25.jpg](https://github.com/aeharding/voyager/assets/32328229/8dccb555-92d7-44f6-b377-d9c7214c3c18)

**Comment by nightgolfer** [comment]
Update: wrote this bug report late last night, was missing some detail. Latest version of PWA on Android.

I've now reset the app cache, and the issue seems to be gone. 

Feel free to close again, and sorry I didn't try this first 🙄

**Comment by nightgolfer** [comment]
I'm just gonna mark this as completed I think. Maybe one takeaway could be the addition of a Clear Cache button in Settings? But don't know if that's possible for a PWA.

**Comment by nightgolfer** [comment]
Sorry, it's still doing it. Reopening.

**Comment by SrivatsanSenthilkumar** [comment]
I don't think the issue is cache related. I face the the same bug but it is not consistent and freely reproducible. And I am on the native app so it is not just a pwa issue.

**Comment by SrivatsanSenthilkumar** [comment]
This happened recently and I managed to grab a screenshot.

![Screenshot_20231019-102125.png](https://github.com/aeharding/voyager/assets/141351084/d070878f-1a45-4f41-a5a1-24f1d4108068)

**Comment by 80avin** [comment]
I'm working on this bug and while I'm not able to recreate it, I think it is caused by this code.
https://github.com/aeharding/voyager/blob/24de23edd5c2125fa13ad04ff5d6a13962efb7aa/src/features/comment/compose/reply/CommentReply.tsx#L107C1-L110

Reasoning:
1. `setCanDismiss` is asynchronous, and at times, it can happen then when `dismiss(reply.comment_view);` runs, canDismiss state hasn't updated.
2. To handle above issue, the [timeout](https://github.com/aeharding/voyager/blob/24de23edd5c2125fa13ad04ff5d6a13962efb7aa/src/features/comment/compose/reply/CommentReply.tsx#L108-L109) was added ( @aeharding  Please confirm )

If this is the issue, then fix would be any of
1. make `setCanDismiss` a wrapper which updates the state and sets the [ref](https://github.com/aeharding/voyager/blob/6006244f2a640b26ebf9df5fc2fe4e7b8903cf3f/src/features/shared/DynamicDismissableModal.tsx#L74-L77) (making it synchronous)
2. OR, add another argument `force` to  `dismiss`, which skips `canDismiss` check.

**Comment by aeharding** [comment]
Sounds good. I can't remember if the problem was that check for `canDismissRef.current` in `dismiss` function, or `canDismiss` as a param of `IonModalAutosizedForOnScreenKeyboard` preventing dismissal.

I'd definitely appreciate a new set of eyes. If we can get rid of the timeout, that would be wonderful.

**Comment by aeharding** [comment]
@80avin any progress on this, or should I unassign you? I might try to take a crack at this.

**Comment by 80avin** [comment]
@aeharding You can try if you feel so.

I'm being a bit busy during weekdays, but on weekend I will complete it. I don't think this one is any big of an issue.

**Comment by aeharding** [comment]
No worries, all yours. Just let me know.
