### ISSUE TITLE
Redgif should be embedded and autoplay

### ISSUE THREAD

**Issue by Juansero29** [aeharding/voyager#671]
Some sites that host gif or webm files do not autoplay (like redgifs.com). This should autoplay like the ones from carbox or other sources. Maybe related to #173?

**Comment by aeharding** [comment]
Linking here for context: https://lemmy.world/comment/6480107

This issue is probably blocked as redgifs is a proprietary platform that requires apps that support it to phone home to get a client key in order to get the video URL to play in-app.

https://github.com/Redgifs/api/wiki/Client-credentials

> client secret, which is a password for your application. Should not be shared.

If anyone knows of an alternative to redgifs that allows some form of hotlinking, or at least no requirement for the app to phone home, I'd be happy to add support.

**Comment by erikpendragon** [comment]
Why not allow the user to input their own API like side loaded Apollo?

**Comment by aeharding** [comment]
Hey! I am working on this right now.

I'm limiting the scope of this task to just redgifs.com, because these kind of sites require a specific implementation.

If you'd like a different specific media site to work, please open a new issue!
