### ISSUE TITLE
[Feature Request] Visual indicator for swiping existing upvote or downvote

### ISSUE THREAD

**Issue by javentous** [aeharding/voyager#708]
### Issue
for longer comments I don't know if I have voted for it or not without scrolling down on the top

### Feature Request
If there was visual indicator maybe when using the swipe gesture or generally after voting to indicate the comment has been voted on that would be great. There is already an indicator for the icon of the up or downvote. If the colour was different or perhaps there was a repeating pattern/shading it would make it more obvious without having to scroll up .

**Comment by 80avin** [comment]
Another way to achieve this could be to always show the buttons in screen area.
If the user has scrolled so that normal position of button is out of view, then the button should move up/down to come in the view while staying within the y-boundaries of the post/comment.

This is similar to how Telegram (android app) shows user avatars in long chats.

**Comment by aeharding** [comment]
You should see a slash through the upvote swipe icon when upvoting/downvoting. However there's a potentially related issue where the icon isn't always showing in the screen for long posts/comments (see: https://github.com/ionic-team/ionic-framework/issues/27839).

**Comment by aeharding** [comment]
The next release should make the swipe icon always visible, so you can see if you've upvoted, downvoted, saved bookmark etc. Hopefully this adequately addresses your concern!

![IMG_FE626F7032E2-1](https://github.com/aeharding/voyager/assets/2166114/273c1586-138e-47f2-ba85-6e73395bad41)

**Comment by javentous** [comment]
Yes, it's wonderful!
