### ISSUE TITLE
Hold account button on nav bar to bring up accounts

### ISSUE THREAD

**Issue by gregside** [aeharding/voyager#85]
A feature that Apollo has that allows for a more seamless way to switch accounts. The current flow is to go to user profile page and then click accounts in the top left.

**Comment by aeharding** [comment]
Good idea! I didn't even know about that.

**Comment by rahulakrishna** [comment]
this gets difficult while in the comments/post view. One major advantage of this account switcher in Apollo was that you could switch accounts while viewing a post to comment from a different account. But this isn't easy in Lemmy because the same post has different `id`s in different instances

http://localhost:5173/posts/lemmy.ml/c/cricket/comments/46834
http://localhost:5173/posts/lemmy.world/c/cricket@lemmy.ml/comments/87541

these are both the same posts viewed through different instances. Fetching data for `46834` while in `lemmy.world` may fetch a completely different post or simply fail. 

Not sure how to proceed with this. I can maybe redirect the user to Home or Profile.

**Comment by aeharding** [comment]
The app should currently reset the tab view if instances changes. So it should work fine. But as you said, you will loose your spot.

A future enhancement could try to resolve the remote post to get its ID.

**Comment by owlboy** [comment]
I wanted to add that in Apollo you could tap up here when authoring a comment to swap accounts.

![image](https://github.com/aeharding/voyager/assets/237349/6420f6c6-d19a-436e-aabf-74ecf84b557f)

The same hurdles exist, but this rounds out the account switching, if a solution is devised.
